# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 801
#data_root: /nfs/bigtensor/add_disk0/ironman/data/cityscapes
data_root: /nfs/bigtensor.cs.stonybrook.edu/add_disk0/ironman/data/cityscapes
mod_scheme: LL-Cp #'LL-R', 'LL-Ct', 'LL-Cp'
delta_rel: 0.000001 #0.1,0.2,0.3,0.4,0.5
clean_rate: 1
#data_root: /nfs/bigtensor.cs.stonybrook.edu/add_disk0/ironman/data/cityscapes
#data_root: /home/phowlader/data/cityscapes
# arguments for training
epochs: 240
batch_size: 1 # per GPU x 4 GPUs
lr: 0.005
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0

# arguments for model
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]

